name: Invalidate Cloudfront

on:
  push:
    branches: [ main ]

jobs:
  invalidation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Invalidate cloudfront
        uses: thiagocerq/cloudfront-invalidations@v1
        env:
          DISTRIBUTIONS_FILE: cloudfront-dists/distributions.txt
          PATHS: '/index.html'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}