name: Upload whitelabel to S3 bucket

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Invalidate
        uses: thiagocerq/cloudfront-invalidations@v1
        args:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTIONS_FILE: s3://cloudfront-dists/distributions.txt
          AWS_REGION: us-east-1


      